services:

  shared_resource:
    container_name: shared
    build:
      context: .
      dockerfile: "Dockerfile.SharedResource"
    stdin_open: true 
    tty: true 

  first_process:
    container_name: p1
    build:
      context: .
      dockerfile: "Dockerfile.Process"
    command: ["1", "p1:10004", "p2:10003", "p3:10002"]
    depends_on:
      - shared_resource
    stdin_open: true 
    tty: true     

  second_process:
    container_name: p2
    build:
      context: .
      dockerfile: "Dockerfile.Process"
    command: ["2", "p1:10004", "p2:10003", "p3:10002"]
    depends_on:
      - shared_resource
    stdin_open: true 
    tty: true        

  third_process:
    container_name: p3
    build:
      context: .
      dockerfile: "Dockerfile.Process"
    command: ["3", "p1:10004", "p2:10003", "p3:10002"]
    depends_on:
      - shared_resource
    stdin_open: true 
    tty: true 
    
